require:
  - rubocop-rails
  - rubocop-capybara
inherit_gem:
  standard: config/base.yml
AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    - bin/bundle

Rails:
  Enabled: true # enable rubocop-rails cops
Rails/I18nLocaleTexts:
  Enabled: false # disable this cop because not using locales for now
Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we will have duplicated gems when dual booting
