version: "3.8"
services:

  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.4
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env'
    volumes:
      - .:/mythographer

volumes:
  redis:
  postgres:
